services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  rabbitmq:
    image: 'rabbitmq:management'
    environment:
      - 'RABBITMQ_DEFAULT_USER=order_user'
      - 'RABBITMQ_DEFAULT_PASS=order_password'
    ports:
      - '5672:5672'
      - '15672:15672'

  mongo:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=order_db'
      - 'MONGO_INITDB_ROOT_USERNAME=order_user'
      - 'MONGO_INITDB_ROOT_PASSWORD=order_password'
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: order_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: order_password
      ME_CONFIG_MONGODB_URL: mongodb://order_user:order_password@mongo:27017/
      ME_CONFIG_BASICAUTH: false
